name: kokoro-fastapi-cpu
services:
  kokoro-tts:
    build:
      context: ../..
      dockerfile: docker/cpu/Dockerfile
    volumes:
      - model-data:/app/api/src/models/v1_0
    ports:
      - "7144:8880"
    environment:
      - PYTHONPATH=/app:/app/api
      - ONNX_NUM_THREADS=8
      - ONNX_INTER_OP_THREADS=4
      - ONNX_EXECUTION_MODE=parallel
      - ONNX_OPTIMIZATION_LEVEL=all
      - ONNX_MEMORY_PATTERN=true
      - ONNX_ARENA_EXTEND_STRATEGY=kNextPowerOfTwo
      - API_LOG_LEVEL=DEBUG
      - NNPACK_DISABLE=1
      - TORCH_BACKENDS_QUANTIZED_ENGINE=qnnpack

volumes:
  model-data:
